# general
batch_size: 128
input_size: 112
embd_shape: 512
sub_name: 'arc_res50'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/ms1m_bin.tfrecord'
binary_img: True
num_classes: 991
num_samples: 7396
epochs: 5
base_lr: 0.0001
w_decay: !!float 5e-4
save_steps: 1000

# test
test_dataset: '/content/drive/MyDrive/chang/arcface-tf2/test_dataset'
